
@startuml

'' header information
header
<font color="red">Cable<b>Labs</b></font>
endheader

'' Use this to hide the foot boxes
hide footbox

skinparam sequenceMessageAlign center
skinparam NoteBorderColor black
'' skinparam BackgroundColor #ddd

skinparam sequence {
	borderColor black
	ArrowColor black
	ActorBorderColor black
	ParticipantBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
}

'' Participants Declaration
Participant "EAP Peer" as P #eee
Participant "EAP Server" as S #eee

autonumber 1 "[##]"

S->P: EAP-Request/EAP-CREDS(Type=ProtoFlow)\n    { Version[=0x1], Protocol[=SPP],\n      Action[=Register], CredInfo[=Cert],\n      CredsParams[=Cert] }
note right: Phase Two\nBegins

P->S: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n    { ProtoData[=PKCS#10], ProtoHeaders[=NULL] }
note left: SPP_Req is a\nPKCS#10 Request\nDER formatted

S->P: EAP-Request/EAP-CREDS(Type=ProtoFlow)\n    { ProtoData[=X.509 Cert], ProtoHeaders[=NULL] }

...

P->S: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n    { << Empty Body >> }
note right: Phase Two\nEnds


@enduml
