
@startuml

'' header information
header
<font color="red">Cable<b>Labs</b></font>
endheader

'' Use this to hide the foot boxes
hide footbox

skinparam sequenceMessageAlign center
skinparam NoteBorderColor black
'' skinparam BackgroundColor #ddd

skinparam sequence {
	borderColor black
	ArrowColor black
	ActorBorderColor black
	ParticipantBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
}

'' Participants Declaration
Participant "EAP Peer" as P #eee
Participant "EAP Server" as S #eee

autonumber 1 "[##]"

S->P: EAP-Request/EAP-CREDS(Type=ProtoFlow)\n    { Protocol(=SPP), Action(=Renewal),\n     [Version(=0x1)], [ProvParam(=Passwd)],\n     [ProtoData(=<Server-Gen-Passwd>)] }
note right: Phase Two\nBegins
note right: This is the\nserver-side\nhalf of the\nnew password

P->S: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n    { << Empty Body >> }
note right: Phase Two\nEnds


@enduml
