
@startuml

'' header information
header
<font color="red">Cable<b>Labs</b></font>
endheader

'' Use this to hide the foot boxes
hide footbox

skinparam sequenceMessageAlign center
skinparam NoteBorderColor black
'' skinparam BackgroundColor #ddd

skinparam sequence {
	borderColor black
	ArrowColor black
	ActorBorderColor black
	ParticipantBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
}

'' Participants Declaration
Participant "EAP Peer" as P #eee
Participant "EAP Server" as S #eee

autonumber 1 "[##]"

S->P: EAP-Request/EAP-CREDS(Type=Provisioning)\n  { Protocol(=SPP), Action(=Register),\n      Creds-Info, Prov-Params(=Symmetric),\n       [ Profile ] }
note right #eee: No shares are\nsent from the\nServer

P->S: EAP-Response/EAP-CREDS(Type=Provisioning)\n  { Prov-Data(=Creds-Data) ] }
note left #eee: Peer sends the\ngenerated secret\nto the Server

'' S->P: EAP-Response/EAP-CREDS(Type=Provisioning)\n  { [ Prov-Data(=Creds-Info,[Creds-Data]) ] }
'' note right #eee: Done ('D')\nbit set

'' P->S: EAP-Response/EAP-CREDS(Type=Provisioning)\n  { << Empty >> }
'' note left #eee: Done ('D')\nbit set

@enduml
