
@startuml

'' header information
header
<font color="red">Cable<b>Labs</b></font>
endheader

'' Use this to hide the foot boxes
hide footbox

skinparam sequenceMessageAlign center
skinparam NoteBorderColor black
'' skinparam BackgroundColor #ddd

skinparam sequence {
	borderColor black
	ArrowColor black
	ActorBorderColor black
	ParticipantBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
}

'' Participants Declaration
Participant "EAP Peer" as P #eee
Participant "EAP Server" as S #eee

autonumber 1 "[##]"

S->P: EAP-Request/EAP-CREDS(Type=ProtoFlow)\n  { Protocol(=SPP), Action, [ Creds-Info ],\n    [ Prov-Params ], [ Profile ]\n    [ Prov-Data(=[Creds-Info],[Creds-Data]) ] }
note right #eee: Sends the Server's\nshare of the secret

P->S: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n  { [ Prov-Data(=[Creds-Data]) ] }
note left #eee: Peer sends its\nshare of the secret

'' S->P: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n  { [ Prov-Data(=Creds-Info,[Creds-Data]) ] }
'' note right #eee: Done ('D')\nbit set

'' P->S: EAP-Response/EAP-CREDS(Type=ProtoFlow)\n  { << Empty >> }
'' note left #eee: Done ('D')\nbit set

@enduml
