
@startuml

'' header information
header
<font color="red">Cable<b>Labs</b></font>
endheader

'' Use this to hide the foot boxes
hide footbox

skinparam sequenceMessageAlign center
skinparam NoteBorderColor black
'' skinparam BackgroundColor #ddd

skinparam sequence {
	borderColor black
	ArrowColor black
	ActorBorderColor black
	ParticipantBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
}

'' Participants Declaration
Participant "EAP Peer" as P #eee
Participant "EAP Server" as S #eee

autonumber 1 "[##]"
S->P: EAP-Request/EAP-CREDS(Type=Validate)\n    { Creds-Info, Challenge-Data }
note right #fff: Phase Three\nBegins

P->S: EAP-Response/EAP-CREDS(Type=Validate)\n    { Challenge-Response }

note right #fff: Phase Three\nEnds


@enduml
